#!/bin/bash
#SBATCH --job-name=pdgemv
#SBATCH --partition=small
#SBATCH --nodes=1
#SBATCH --tasks-per-node=32
#SBATCH --time=00:10:00
#SBATCH --mem=64GB
#SBATCH --account=classes
#SBATCH --output=pdgemv.out
#SBATCH --error=pdgemv.err

# load openmpi module
module load rhel7/openmpi/4.0.2-gcc-4.8

mpicxx -o pdgemv pdgemv.cpp

# run code
mpirun -n 4 ./pdgemv 4 4 4 1
